CREATE SCHEMA IF NOT EXISTS `ICF`;

USE `ICF`;
CREATE TABLE IF NOT EXISTS `Users`(
	`Id` INT NOT NULL PRIMARY KEY,
    `Rank` INT NOT NULL,
    `Age` INT NOT NULL,
    `Role` VARCHAR(50) NOT NULL,
    `Position` VARCHAR(50) NOT NULL,
    `Status` BOOLEAN NOT NULL
);